### ISSUE TITLE
Win 7 crashes

### ISSUE THREAD

**Issue by Extent421** [nedrysoft/pingnoo#91]
Just downloaded 2021.04.30-develop, and I've got some crashes.  First one happens if if ICMP Socket is chosen for the engine, as soon as I click start it creates the results window and then dies 

Faulting application name: Pingnoo.exe, version: 0.0.0.0, time stamp: 0x608bebce
Faulting module name: ICMPSocket.dll, version: 0.0.0.0, time stamp: 0x608bea56
Exception code: 0xc0000005
Fault offset: 0x0000000000001737
Faulting process id: 0x17f4
Faulting application start time: 0x01d78cd0be36af20
Faulting application path: C:\Program Files\nedrysoft.com\Pingnoo\Pingnoo.exe
Faulting module path: C:\Program Files\nedrysoft.com\Pingnoo\ICMPSocket.dll
Report Id: 07cd0fd0-f8c4-11eb-8f2a-d0c5d3848394

Switching the engine to ICMPAPI after hitting start it churns for a minute and then seems to begin working normally, except that it doesn't seem to detect the correct route ( compared to ping plotter on the same machine, and a different pingnoo instance running on an ubuntu box on the same network) it turns a 13 hop route into a 63 hop trace where all hops are just full packet loss after hop 12.  Left running for a few minutes the window will silently close, with no error or message.

**Comment by fizzyade** [comment]
I think I’ve fixed these issues, but I haven’t built windows binaries because I was in the middle of some other changes, unfortunately I’ve been quite unwell for the past few months, so I haven’t got back to continuing where I left off.

I will trigger a windows build and try to push a pre-release windows build tonight to see if that fixes your issues, I’ll let you know once I’ve done it here.

Thanks for the report, hopefully I’ve fixed what you have described, I reworked the code for route discovery and it now reports the route as it’s being discovered rather than just appearing to freeze.

**Comment by Extent421** [comment]
no worries, it works in linux which is where I really need it.  Just wanted to be sure there was a report logged for it.

**Comment by fizzyade** [comment]
I’ll try to push Linux binaries as well then, the new version is worth using purely for the responsive UI when detecting the route!  I think I fixed the 64 hop thing as well.

**Comment by fizzyade** [comment]
@Extent421 I have uploaded Windows 32-bit, 64-bit and portable versions as a pre-release, please try this version and let me know if it works or not for you.

https://github.com/nedrysoft/pingnoo/releases/tag/2021.06.23-develop

**Comment by Extent421** [comment]
I can see it trying to work, but route detection seems to be about the same.  It displays the first 3 or 4 hops, and then freezes just like before, it popped back once at 53 hops and then froze again before capping out at 63 hops, and still not getting the right route.

But it's been running for about an hour now without the window disappearing though, so that's fixed.

ICMP Socket crash still happens with the same code and offset,

**Comment by fizzyade** [comment]
If you have windows firewall enabled, can you try temporarily disabling it and then try ICMP socket again.

ICMPAPI seems to pass through the firewall without any special treatment, ICMP socket under windows doesn’t though.   I will have to set up a windows 7 VM to test.

**Comment by Extent421** [comment]
turning off the firewall gives the same crash.  I don't remember seeing the allow access popup for it, so it must be dying before that point.

**Comment by garry-ut99** [comment]
> I can see it trying to work, but route detection seems to be about the same. 

Same here.

> ICMP Socket crash still happens

Same for me, initially the program was working fine for several runs, but now it crashes always after pressing Start.

<br>

Program good, but useless until the bugs fixed.
